include_guard(GLOBAL)

function(project_find_dependencies)
    find_package(Qt6 6.11.1 EXACT REQUIRED COMPONENTS Core Gui Network Qml Quick QuickControls2 Test)
    find_package(fmt CONFIG REQUIRED)
    find_package(OpenSSL REQUIRED)
    find_package(LibLZMA REQUIRED)
    find_package(Protobuf CONFIG REQUIRED)
    find_package(spdlog CONFIG REQUIRED)
    find_package(ZLIB REQUIRED)

    if(BUILD_TESTING)
        find_package(GTest CONFIG REQUIRED)
    endif()
endfunction()
